# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
  nginx:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ../nginx
    # маршрутизируем порты
    ports:
      - "80:80"
      - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes_from:
      - php
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ../php
    # этот образ будет общаться с mysql
    links:
      - mysql
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    #volumes:
    #    - ./mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: secret
