# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
  nginx:
    image: rodionoff/nginx
    # маршрутизируем порты
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - php
    # nginx должен общаться с php контейнером
    links:
      - php
  php:
    image: rodionoff/php-fpm
    # этот образ будет общаться с mysql
    links:
      - mysql
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    # Порты тоже не нужны: снаружи в БД ходить не будем
    #ports:
    #  - "33061:3306"
    # Не монтируем sql, т.к это приводит к проблемам на винде. На prod все равно будет bare metal
    #volumes:
    #    - ./mysql:/var/lib/mysql
    # чиним изменившийся режим авторизации в MySQL 8
    command: --default-authentication-plugin=mysql_native_password
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: myapp
